terraform {
  required_version = "= 0.13.7"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0" # v5 supports Terraform >= 0.13; v6 needs Terraform 1.x
    }
    archive = {
      source  = "hashicorp/archive"
      version = "~> 2.2.0"
    }
  }

  # The backend (local, state kept in this repository) is generated by Terragrunt
  # into backend.tf — see terragrunt.hcl.
}
